version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    depends_on:
      - mongo
    networks:
      - paintedpoker 

  mongo:
    image: mongo:6.0
    container_name: paintedpokermongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - paintedpoker 

volumes:
  mongo-data:
  mongo-config:
  
networks:
  paintedpoker:
    driver: bridge